package net.swissindex.ws.nonpharma;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ws_NonPharma_V101", targetNamespace = "http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101", wsdlLocation = "file:/Users/marco/Development/workspace-elexis-productive/net.swissindex.format/rsc/wsdl/ws_NonPharma_V101.wsdl")
public class WsNonPharmaV101 extends Service {
	
	private final static URL WSNONPHARMAV101_WSDL_LOCATION;
	private final static WebServiceException WSNONPHARMAV101_EXCEPTION;
	private final static QName WSNONPHARMAV101_QNAME = new QName(
		"http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101", "ws_NonPharma_V101");
	
	static {
		URL url = null;
		WebServiceException e = null;
		url = WsNonPharmaV101.class.getResource("ws_NonPharma_V101.wsdl");
		WSNONPHARMAV101_WSDL_LOCATION = url;
		WSNONPHARMAV101_EXCEPTION = e;
	}
	
	public WsNonPharmaV101(){
		super(__getWsdlLocation(), WSNONPHARMAV101_QNAME);
	}
	
	public WsNonPharmaV101(WebServiceFeature... features){
		super(__getWsdlLocation(), WSNONPHARMAV101_QNAME, features);
	}
	
	public WsNonPharmaV101(URL wsdlLocation){
		super(wsdlLocation, WSNONPHARMAV101_QNAME);
	}
	
	public WsNonPharmaV101(URL wsdlLocation, WebServiceFeature... features){
		super(wsdlLocation, WSNONPHARMAV101_QNAME, features);
	}
	
	public WsNonPharmaV101(URL wsdlLocation, QName serviceName){
		super(wsdlLocation, serviceName);
	}
	
	public WsNonPharmaV101(URL wsdlLocation, QName serviceName, WebServiceFeature... features){
		super(wsdlLocation, serviceName, features);
	}
	
	/**
	 * 
	 * @return returns WsNonPharmaV101Soap
	 */
	@WebEndpoint(name = "ws_NonPharma_V101Soap")
	public WsNonPharmaV101Soap getWsNonPharmaV101Soap(){
		return super.getPort(
			new QName("http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101",
				"ws_NonPharma_V101Soap"), WsNonPharmaV101Soap.class);
	}
	
	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
	 *            Supported features not in the <code>features</code> parameter will have their
	 *            default values.
	 * @return returns WsNonPharmaV101Soap
	 */
	@WebEndpoint(name = "ws_NonPharma_V101Soap")
	public WsNonPharmaV101Soap getWsNonPharmaV101Soap(WebServiceFeature... features){
		return super.getPort(
			new QName("http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101",
				"ws_NonPharma_V101Soap"), WsNonPharmaV101Soap.class, features);
	}
	
	/**
	 * 
	 * @return returns WsNonPharmaV101Soap
	 */
	@WebEndpoint(name = "ws_NonPharma_V101Soap12")
	public WsNonPharmaV101Soap getWsNonPharmaV101Soap12(){
		return super.getPort(new QName(
			"http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101",
			"ws_NonPharma_V101Soap12"), WsNonPharmaV101Soap.class);
	}
	
	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.
	 *            Supported features not in the <code>features</code> parameter will have their
	 *            default values.
	 * @return returns WsNonPharmaV101Soap
	 */
	@WebEndpoint(name = "ws_NonPharma_V101Soap12")
	public WsNonPharmaV101Soap getWsNonPharmaV101Soap12(WebServiceFeature... features){
		return super.getPort(new QName(
			"http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101",
			"ws_NonPharma_V101Soap12"), WsNonPharmaV101Soap.class, features);
	}
	
	private static URL __getWsdlLocation(){
		if (WSNONPHARMAV101_EXCEPTION != null) {
			throw WSNONPHARMAV101_EXCEPTION;
		}
		return WSNONPHARMAV101_WSDL_LOCATION;
	}
	
}
