
package net.swissindex.ws.nonpharma;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ws_NonPharma_V101Soap", targetNamespace = "http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WsNonPharmaV101Soap {


    /**
     * <p></p><p><b>Schema Output:</b> Click <a href='../schema/SwissindexNonPharma_out_V101.xsd'>here</a>
     * 
     * @param lang
     * @return
     *     returns net.swissindex.ws.nonpharma.NONPHARMA
     */
    @WebMethod(operationName = "DownloadAll", action = "http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101/DownloadAll")
    @WebResult(name = "NONPHARMA", targetNamespace = "http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101", partName = "DownloadAllResult")
    public NONPHARMA downloadAll(
        @WebParam(name = "lang", targetNamespace = "http://swissindex.e-mediat.net/SwissindexNonPharma_out_V101", partName = "lang")
        String lang);

}
