//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 09:14:10 AM MESZ 
//


package com.ywesee.oddb2xml.article;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}PHAR"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SMCAT" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SMNO" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SALECD"/>
 *         &lt;choice minOccurs="0">
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}COOL"/>
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}LIMPTS"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}CDBG"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}BG"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}QTY" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}DSCRD"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}DSCRF"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SORTD"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SORTF"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SYN1D"/>
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SYN1F"/>
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SLOPLUS"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}ARTCOMP"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}ARTBAR"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}ARTPRI" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}ARTINS" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "phar",
    "smcat",
    "smno",
    "salecd",
    "cool",
    "limpts",
    "cdbg",
    "bg",
    "qty",
    "dscrd",
    "dscrf",
    "sortd",
    "sortf",
    "syn1D",
    "syn1F",
    "sloplus",
    "artcomp",
    "artbar",
    "artpri",
    "artins"
})
@XmlRootElement(name = "ART")
public class ART {

    @XmlElement(name = "PHAR", required = true)
    protected String phar;
    @XmlElement(name = "SMCAT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String smcat;
    @XmlElement(name = "SMNO")
    protected BigInteger smno;
    @XmlElement(name = "SALECD", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String salecd;
    @XmlElement(name = "COOL")
    protected BigInteger cool;
    @XmlElement(name = "LIMPTS")
    protected BigInteger limpts;
    @XmlElement(name = "CDBG", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String cdbg;
    @XmlElement(name = "BG", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String bg;
    @XmlElement(name = "QTY")
    protected String qty;
    @XmlElement(name = "DSCRD", required = true)
    protected String dscrd;
    @XmlElement(name = "DSCRF", required = true)
    protected String dscrf;
    @XmlElement(name = "SORTD", required = true)
    protected String sortd;
    @XmlElement(name = "SORTF", required = true)
    protected String sortf;
    @XmlElement(name = "SYN1D")
    protected String syn1D;
    @XmlElement(name = "SYN1F")
    protected String syn1F;
    @XmlElement(name = "SLOPLUS")
    protected BigInteger sloplus;
    @XmlElement(name = "ARTCOMP", required = true)
    protected ARTCOMP artcomp;
    @XmlElement(name = "ARTBAR", required = true)
    protected ARTBAR artbar;
    @XmlElement(name = "ARTPRI")
    protected List<ARTPRI> artpri;
    @XmlElement(name = "ARTINS")
    protected ARTINS artins;
    @XmlAttribute(name = "DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dt;

    /**
     * Gets the value of the phar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPHAR() {
        return phar;
    }

    /**
     * Sets the value of the phar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPHAR(String value) {
        this.phar = value;
    }

    /**
     * Gets the value of the smcat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSMCAT() {
        return smcat;
    }

    /**
     * Sets the value of the smcat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSMCAT(String value) {
        this.smcat = value;
    }

    /**
     * Gets the value of the smno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSMNO() {
        return smno;
    }

    /**
     * Sets the value of the smno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSMNO(BigInteger value) {
        this.smno = value;
    }

    /**
     * Gets the value of the salecd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSALECD() {
        return salecd;
    }

    /**
     * Sets the value of the salecd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSALECD(String value) {
        this.salecd = value;
    }

    /**
     * Gets the value of the cool property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCOOL() {
        return cool;
    }

    /**
     * Sets the value of the cool property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCOOL(BigInteger value) {
        this.cool = value;
    }

    /**
     * Gets the value of the limpts property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLIMPTS() {
        return limpts;
    }

    /**
     * Sets the value of the limpts property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLIMPTS(BigInteger value) {
        this.limpts = value;
    }

    /**
     * Gets the value of the cdbg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCDBG() {
        return cdbg;
    }

    /**
     * Sets the value of the cdbg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCDBG(String value) {
        this.cdbg = value;
    }

    /**
     * Gets the value of the bg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBG() {
        return bg;
    }

    /**
     * Sets the value of the bg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBG(String value) {
        this.bg = value;
    }

    /**
     * Gets the value of the qty property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQTY() {
        return qty;
    }

    /**
     * Sets the value of the qty property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQTY(String value) {
        this.qty = value;
    }

    /**
     * Gets the value of the dscrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSCRD() {
        return dscrd;
    }

    /**
     * Sets the value of the dscrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSCRD(String value) {
        this.dscrd = value;
    }

    /**
     * Gets the value of the dscrf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSCRF() {
        return dscrf;
    }

    /**
     * Sets the value of the dscrf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSCRF(String value) {
        this.dscrf = value;
    }

    /**
     * Gets the value of the sortd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSORTD() {
        return sortd;
    }

    /**
     * Sets the value of the sortd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSORTD(String value) {
        this.sortd = value;
    }

    /**
     * Gets the value of the sortf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSORTF() {
        return sortf;
    }

    /**
     * Sets the value of the sortf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSORTF(String value) {
        this.sortf = value;
    }

    /**
     * Gets the value of the syn1D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYN1D() {
        return syn1D;
    }

    /**
     * Sets the value of the syn1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYN1D(String value) {
        this.syn1D = value;
    }

    /**
     * Gets the value of the syn1F property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYN1F() {
        return syn1F;
    }

    /**
     * Sets the value of the syn1F property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYN1F(String value) {
        this.syn1F = value;
    }

    /**
     * Gets the value of the sloplus property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSLOPLUS() {
        return sloplus;
    }

    /**
     * Sets the value of the sloplus property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSLOPLUS(BigInteger value) {
        this.sloplus = value;
    }

    /**
     * Gets the value of the artcomp property.
     * 
     * @return
     *     possible object is
     *     {@link ARTCOMP }
     *     
     */
    public ARTCOMP getARTCOMP() {
        return artcomp;
    }

    /**
     * Sets the value of the artcomp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ARTCOMP }
     *     
     */
    public void setARTCOMP(ARTCOMP value) {
        this.artcomp = value;
    }

    /**
     * Gets the value of the artbar property.
     * 
     * @return
     *     possible object is
     *     {@link ARTBAR }
     *     
     */
    public ARTBAR getARTBAR() {
        return artbar;
    }

    /**
     * Sets the value of the artbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link ARTBAR }
     *     
     */
    public void setARTBAR(ARTBAR value) {
        this.artbar = value;
    }

    /**
     * Gets the value of the artpri property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the artpri property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getARTPRI().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ARTPRI }
     * 
     * 
     */
    public List<ARTPRI> getARTPRI() {
        if (artpri == null) {
            artpri = new ArrayList<ARTPRI>();
        }
        return this.artpri;
    }

    /**
     * Gets the value of the artins property.
     * 
     * @return
     *     possible object is
     *     {@link ARTINS }
     *     
     */
    public ARTINS getARTINS() {
        return artins;
    }

    /**
     * Sets the value of the artins property.
     * 
     * @param value
     *     allowed object is
     *     {@link ARTINS }
     *     
     */
    public void setARTINS(ARTINS value) {
        this.artins = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDT() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDT(String value) {
        this.dt = value;
    }

}
