//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 09:14:10 AM MESZ 
//


package com.ywesee.oddb2xml.limitation;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SwissmedicNo5"/>
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SwissmedicNo8"/>
 *         &lt;/choice>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}IT"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}LIMTYP"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}LIMVAL"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}LIMNAMEBAG"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}LIMNIV"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}DSCRD"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}DSCRF"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}VDAT"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "swissmedicNo5",
    "swissmedicNo8",
    "it",
    "limtyp",
    "limval",
    "limnamebag",
    "limniv",
    "dscrd",
    "dscrf",
    "vdat"
})
@XmlRootElement(name = "LIM")
public class LIM {

    @XmlElement(name = "SwissmedicNo5")
    protected BigInteger swissmedicNo5;
    @XmlElement(name = "SwissmedicNo8")
    protected BigInteger swissmedicNo8;
    @XmlElement(name = "IT", required = true)
    protected String it;
    @XmlElement(name = "LIMTYP", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String limtyp;
    @XmlElement(name = "LIMVAL", required = true)
    protected String limval;
    @XmlElement(name = "LIMNAMEBAG", required = true)
    protected String limnamebag;
    @XmlElement(name = "LIMNIV", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String limniv;
    @XmlElement(name = "DSCRD", required = true)
    protected String dscrd;
    @XmlElement(name = "DSCRF", required = true)
    protected String dscrf;
    @XmlElement(name = "VDAT", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String vdat;
    @XmlAttribute(name = "DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dt;

    /**
     * Gets the value of the swissmedicNo5 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSwissmedicNo5() {
        return swissmedicNo5;
    }

    /**
     * Sets the value of the swissmedicNo5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSwissmedicNo5(BigInteger value) {
        this.swissmedicNo5 = value;
    }

    /**
     * Gets the value of the swissmedicNo8 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSwissmedicNo8() {
        return swissmedicNo8;
    }

    /**
     * Sets the value of the swissmedicNo8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSwissmedicNo8(BigInteger value) {
        this.swissmedicNo8 = value;
    }

    /**
     * Gets the value of the it property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIT() {
        return it;
    }

    /**
     * Sets the value of the it property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIT(String value) {
        this.it = value;
    }

    /**
     * Gets the value of the limtyp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIMTYP() {
        return limtyp;
    }

    /**
     * Sets the value of the limtyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIMTYP(String value) {
        this.limtyp = value;
    }

    /**
     * Gets the value of the limval property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIMVAL() {
        return limval;
    }

    /**
     * Sets the value of the limval property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIMVAL(String value) {
        this.limval = value;
    }

    /**
     * Gets the value of the limnamebag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIMNAMEBAG() {
        return limnamebag;
    }

    /**
     * Sets the value of the limnamebag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIMNAMEBAG(String value) {
        this.limnamebag = value;
    }

    /**
     * Gets the value of the limniv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIMNIV() {
        return limniv;
    }

    /**
     * Sets the value of the limniv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIMNIV(String value) {
        this.limniv = value;
    }

    /**
     * Gets the value of the dscrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSCRD() {
        return dscrd;
    }

    /**
     * Sets the value of the dscrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSCRD(String value) {
        this.dscrd = value;
    }

    /**
     * Gets the value of the dscrf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSCRF() {
        return dscrf;
    }

    /**
     * Sets the value of the dscrf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSCRF(String value) {
        this.dscrf = value;
    }

    /**
     * Gets the value of the vdat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVDAT() {
        return vdat;
    }

    /**
     * Sets the value of the vdat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVDAT(String value) {
        this.vdat = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDT() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDT(String value) {
        this.dt = value;
    }

}
