//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 09:14:10 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ywesee.oddb2xml.product;
