//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.27 at 09:14:10 AM MESZ 
//


package com.ywesee.oddb2xml.product;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}GTIN"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}PRODNO" minOccurs="0"/>
 *         &lt;sequence minOccurs="0">
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}DSCRD"/>
 *           &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}DSCRF"/>
 *         &lt;/sequence>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}ADINFD" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}ADINFF" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}GENCD" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}ATC" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}IT" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}ORPH" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}CPT"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}PackGrSwissmedic" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}EinheitSwissmedic" minOccurs="0"/>
 *         &lt;element ref="{http://wiki.oddb.org/wiki.php?pagename=Swissmedic.Datendeklaration}SubstanceSwissmedic" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="DT" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gtin",
    "prodno",
    "dscrd",
    "dscrf",
    "adinfd",
    "adinff",
    "gencd",
    "atc",
    "it",
    "orph",
    "cpt",
    "packGrSwissmedic",
    "einheitSwissmedic",
    "substanceSwissmedic"
})
@XmlRootElement(name = "PRD")
public class PRD {

    @XmlElement(name = "GTIN", required = true)
    protected BigInteger gtin;
    @XmlElement(name = "PRODNO")
    protected BigInteger prodno;
    @XmlElement(name = "DSCRD")
    protected String dscrd;
    @XmlElement(name = "DSCRF")
    protected String dscrf;
    @XmlElement(name = "ADINFD")
    protected String adinfd;
    @XmlElement(name = "ADINFF")
    protected String adinff;
    @XmlElement(name = "GENCD")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String gencd;
    @XmlElement(name = "ATC")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String atc;
    @XmlElement(name = "IT")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String it;
    @XmlElement(name = "ORPH")
    protected Boolean orph;
    @XmlElement(name = "CPT", required = true)
    protected CPT cpt;
    @XmlElement(name = "PackGrSwissmedic")
    protected String packGrSwissmedic;
    @XmlElement(name = "EinheitSwissmedic")
    protected String einheitSwissmedic;
    @XmlElement(name = "SubstanceSwissmedic")
    protected String substanceSwissmedic;
    @XmlAttribute(name = "DT", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dt;

    /**
     * Gets the value of the gtin property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGTIN() {
        return gtin;
    }

    /**
     * Sets the value of the gtin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGTIN(BigInteger value) {
        this.gtin = value;
    }

    /**
     * Gets the value of the prodno property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPRODNO() {
        return prodno;
    }

    /**
     * Sets the value of the prodno property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPRODNO(BigInteger value) {
        this.prodno = value;
    }

    /**
     * Gets the value of the dscrd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSCRD() {
        return dscrd;
    }

    /**
     * Sets the value of the dscrd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSCRD(String value) {
        this.dscrd = value;
    }

    /**
     * Gets the value of the dscrf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDSCRF() {
        return dscrf;
    }

    /**
     * Sets the value of the dscrf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDSCRF(String value) {
        this.dscrf = value;
    }

    /**
     * Gets the value of the adinfd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADINFD() {
        return adinfd;
    }

    /**
     * Sets the value of the adinfd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADINFD(String value) {
        this.adinfd = value;
    }

    /**
     * Gets the value of the adinff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADINFF() {
        return adinff;
    }

    /**
     * Sets the value of the adinff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADINFF(String value) {
        this.adinff = value;
    }

    /**
     * Gets the value of the gencd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGENCD() {
        return gencd;
    }

    /**
     * Sets the value of the gencd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGENCD(String value) {
        this.gencd = value;
    }

    /**
     * Gets the value of the atc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getATC() {
        return atc;
    }

    /**
     * Sets the value of the atc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setATC(String value) {
        this.atc = value;
    }

    /**
     * Gets the value of the it property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIT() {
        return it;
    }

    /**
     * Sets the value of the it property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIT(String value) {
        this.it = value;
    }

    /**
     * Gets the value of the orph property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isORPH() {
        return orph;
    }

    /**
     * Sets the value of the orph property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setORPH(Boolean value) {
        this.orph = value;
    }

    /**
     * Gets the value of the cpt property.
     * 
     * @return
     *     possible object is
     *     {@link CPT }
     *     
     */
    public CPT getCPT() {
        return cpt;
    }

    /**
     * Sets the value of the cpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link CPT }
     *     
     */
    public void setCPT(CPT value) {
        this.cpt = value;
    }

    /**
     * Gets the value of the packGrSwissmedic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackGrSwissmedic() {
        return packGrSwissmedic;
    }

    /**
     * Sets the value of the packGrSwissmedic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackGrSwissmedic(String value) {
        this.packGrSwissmedic = value;
    }

    /**
     * Gets the value of the einheitSwissmedic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEinheitSwissmedic() {
        return einheitSwissmedic;
    }

    /**
     * Sets the value of the einheitSwissmedic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEinheitSwissmedic(String value) {
        this.einheitSwissmedic = value;
    }

    /**
     * Gets the value of the substanceSwissmedic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubstanceSwissmedic() {
        return substanceSwissmedic;
    }

    /**
     * Sets the value of the substanceSwissmedic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubstanceSwissmedic(String value) {
        this.substanceSwissmedic = value;
    }

    /**
     * Gets the value of the dt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDT() {
        return dt;
    }

    /**
     * Sets the value of the dt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDT(String value) {
        this.dt = value;
    }

}
